---
author: Muxin Hua
date: 2023-01-26
categories: "Asking Good Questions"
title: Asking Good Questions
---

## Prompt:

Asking good questions is a valuable skill to have - asking questions in an online setting is both easier and harder than asking questions in person: we can prepare to ask a question but we are also expected to prepare.
The links posted here give some advice on how to ask good questions:

- stackoverflow's [Asking a good question](http://stackoverflow.com/help/how-to-ask)

- R's [Posting guidelines](https://www.r-project.org/posting-guide.html)

- [minimal complete verifiable example](https://stackoverflow.com/help/mcve), [minimal reproducible example](https://www.tidyverse.org/help/)

Follow these links and read through the advice given, then

1. **Pick at least one question from stackoverflow or the R help and answer it.**

Write a blog post answering the following questions: 

2. **Document which question you answered (link to your answer).**        

https://stackoverflow.com/questions/75344221/how-to-combine-2-lists-in-equal-parts/75363707#75363707

3. **Relate your experience of answering the question to your reading.**

I chose a question specifically about merging list. The author nicely and clearly stated the problem. According to "How do I ask a good question" in stackoverflow, it does very good on *help others reproduce the problem*, because the author gave example of how the results should look like, that makes the problem comprehensible. The author also didn't specify the language to solve the problem, which looks more like asking for help in "logic" behind the question rather than limiting to "getting the answer". This should be inspiring to the ones need such help.

<!--Go to [https://github.com/Stat585-at-ISU/blog](https://github.com/Stat585-at-ISU/blog) for instructions about how to prepare and submit your blog post.-->
<!-- Instructions to follow. -->