---
author: Yingchao Zhou
date: 2023-01-26
categories: "Asking Good Questions"
title: Asking Good Questions
---

## Prompt:

Asking good questions is a valuable skill to have - asking questions in an online setting is both easier and harder than asking questions in person: we can prepare to ask a question but we are also expected to prepare.
The links posted here give some advice on how to ask good questions:

- stackoverflow's [Asking a good question](http://stackoverflow.com/help/how-to-ask)

- R's [Posting guidelines](https://www.r-project.org/posting-guide.html)

- [minimal complete verifiable example](https://stackoverflow.com/help/mcve), [minimal reproducible example](https://www.tidyverse.org/help/)

Follow these links and read through the advice given, then

1. **Pick at least one question from stackoverflow or the R help and answer it.**

Write a blog post answering the following questions: 

2. **Document which question you answered (link to your answer).**  

I answered one question from stackoverflow about plotting data with longitude and latitude on a map. Here is the link: [https://stackoverflow.com/questions/75228497/how-can-i-plot-a-map-using-ggplot2-that-includes-the-latitude-and-longitude-of-t/75229784#75229784](https://stackoverflow.com/questions/75228497/how-can-i-plot-a-map-using-ggplot2-that-includes-the-latitude-and-longitude-of-t/75229784#75229784)

3. **Relate your experience of answering the question to your reading. **  

ome questions I see on stackoverflow are long and messy, with many code chunks and I feel hard to read and understand them. Although the titles seem not too difficult, after clicking in, I gave up reading them. Giving a minimal reproducible example can really make it much easier for answerers.  


<!--Go to [https://github.com/Stat585-at-ISU/blog](https://github.com/Stat585-at-ISU/blog) for instructions about how to prepare and submit your blog post.-->
Instructions to follow.
