project:
  type: website

website:
  title: "Stat 585"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: schedule.html
        text: Schedule
      - href: labs.qmd
        text: Labs
      - href: blog.qmd
        text: Blog
      - href: projects.qmd
        text: Projects
      - href: https://canvas.iastate.edu/courses/90437
        text: Canvas (ISU)
      - href: https://canvas.unl.edu/courses/150086
        text: Canvas (UNL)

format:
  html:
    theme: cosmo
    css: ["styles.css", "css/extra.css"]
    toc: true

execute:
  freeze: auto 

editor: source

