project:
  type: website
  pre-render: 
    - fix-blog.R
  output-dir: docs
  
website:
  title: "Stat 585"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: schedule.html
        text: Schedule
      - href: blog.qmd
        text: Blog
      - href: labs.qmd
        text: Labs
      - href: projects.qmd
        text: Projects
      - href: projects/project-samples.qmd
        text: Samples
      - href: https://canvas.iastate.edu/courses/98137
        text: Canvas (ISU)
      - href: https://canvas.unl.edu/courses/150086
        text: Canvas (UNL)

format:
  html:
    theme: united #superhero
    css: ["styles.css"]
    toc: true

execute:
  cache: true
  freeze: auto 

editor: source

