project:
  type: website
  pre-render: 
    - fix-blog.R
  output-dir: docs
  
website:
  title: "Stat 585"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: schedule.html
        text: Schedule
      - href: blog.qmd
        text: Blog
      - href: projects.qmd
        text: Projects
      - href: https://canvas.iastate.edu/courses/90437
        text: Canvas (ISU)
      - href: https://canvas.unl.edu/courses/150086
        text: Canvas (UNL)

format:
  html:
    theme: united #superhero
    css: ["styles.css"]
    toc: true

execute:
  freeze: auto 

editor: source

