---
title: "Schedule"
---

The full syllabus is available [here](syllabus.pdf)

## Course Topics

Week | Topic | Notes
----- | --------------- | ------------------------------------------------------
1 - 2     | Working Environment and Review Git, GitHub, and R Markdown   | **Jan 17 ** [Course intro & syllabus](../materials-2023/00_getting-started/slides.html) \| [Collaborations - test case](../materials-2023/01_collaborative-environment/01_test-case.html) \| data: [2015 BRFSS data for Iowa](../materials-2023/01_collaborative-environment/data/brfss_iowa.csv) \| Code book: [BRFSS Codebook 2015](https://www.cdc.gov/brfss/annual_data/2015/pdf/codebook15_llcp.pdf)
&nbsp;    | &nbsp;                                                       | **Jan 19** [Collaborations - test case - part 2](../materials-2023/01_collaborative-environment/01_test-case.html#16) \| [a solution to the test case](../materials-2023/01_collaborative-environment/02_test-case-solution.html)
&nbsp;    | &nbsp;                                                       | **Jan 24** [tools for collaborations](../materials-2023/01_collaborative-environment/03_tools-of-the-trade.html) \| [R Markdown refresher](https://ds202-at-isu.github.io/materials/01_collaborative-environment/03_rmarkdown.html#1) \| [to add or not to add? that is the git-tion](../materials-2023/01_collaborative-environment/05_responsible_git.html)
3 - 5     | Data structures in R: factors, lists, trees                  | **Jan 26** [Results from R & friends](../materials-2023/02_tidyverse/01b_r-and-friends.html) \| [Reviewing elements of the tidyverse: ggplot2, dplyr, tidyr with solutions](../materials-2023/02_tidyverse/01_intro.html)
&nbsp;    | &nbsp;                                                       | **Jan 31** [Reviewing elements of the tidyverse: ggplot2, dplyr, tidyr with solutions](../materials-2023/02_tidyverse/01_intro.html) 
&nbsp;    | &nbsp;                                                       | **Feb 2** [Lab #1](labs/01-slides.qmd)
&nbsp;    | &nbsp;                                                       | **Feb 7** [Review of basic R types and structures, first look at lists](../materials-2023/03_data-structures/01_data-structures.html), [code](../materials-2023/code/code-2023-02-07.R)
&nbsp;    | &nbsp;                                                       | **Feb 9** [ List objects](../materials-2023/03_data-structures/01_data-structures.html#18)
 &nbsp;        | &nbsp;                                                       | **Feb 14** [ Recap of Blog 3](../materials-2023/99_recaps/03_blog-recap.html), [List objects](../materials-2023/03_data-structures/01_data-structures.html#26), [code](../materials-2023/code/code-2023-02-14.R)
&nbsp;     |   &nbsp;     | **Feb 16** [Lab #2](labs/02_lab_2023.html)
6         | Split-apply-combine strategies with lists, Review of functional programming, conditionals, loops.                    | **Feb 21** [Dates and time](../materials-2023/03_data-structures/02_date-and-time.html), [code](../materials-2023/code/code-2023-02-21.R)  
&nbsp;    | &nbsp;                                                       | **Feb 23** [Reviewing Functions](../materials-2023/04_functional-programming/01_functions.html), [Split-apply-combine with lists](../materials-2023/04_functional-programming/02b_purrr.html), [code](../materials-2023/code/code-2023-02-23.R)  
7-8       | Package system in R                                          | **Feb 28** [A first R package](../materials-2023/09_packages/01_r-packages.html), [Let's do that again with litr](https://jacobbien.github.io/litr-project/index.html), [code](../materials-2023/code/code-2023-02-28.R)
&nbsp;    | &nbsp;                                                       | **Mar 2** [Lab #3](labs/03-lab-slides.qmd)
&nbsp;    | &nbsp;                                                       | **Mar 7** [Data in packages](../materials-2023/09_packages/02_r-packages-data.html), [Package dependencies](../materials-2023/09_packages/01_r-packages.html#11)
&nbsp;    | &nbsp;                                                       | **Mar 9** [Logistics](../materials-2023/news/news-2023-03-09.html), [Package dependencies](../materials-2023/09_packages/01_r-packages-data.html#11), [The error fixing cycle](../materials-2023/09_packages/02_r-packages-data.html)
&nbsp;    | &nbsp;                                                       | **Mar 21** [Let's do that again: Packages in R](../materials-2023/09_packages/01_r-packages.html#5), [Data in packages](../materials-2023/09_packages/02_r-packages-data-no-turns.html)
9-10      | Testing code & Critical analysis of code                     | **Mar 23** [Connecting a package to Github](https://stat585-at-isu.github.io/materials-2023/09_packages/02_r-packages-data-no-turns.html#15), [Continuous Integration](https://stat585-at-isu.github.io/materials-2023/09_packages/02_r-packages-data-no-turns.html#14), [Unit testing](../materials-2023/08_testing-code/02_testing-code.html)
&nbsp;    | &nbsp;                                                       | **Mar 28** [The one where Austria was abducted ...](../materials-2023/08_testing-code/02_testing-code.html#15)
11        | Web scraping, working with text: awk and grep      | **Mar 30** [One more set of tests](https://stat585-at-isu.github.io/materials-2023/08_testing-code/02_testing-code.html#32), [Intro to web-scraping](../materials-2023/11_web-scraping/01_web-scraping.html)
&nbsp;    | &nbsp;                                                       | **Apr 4** [Web-scraping - your turn :)](../materials-2023/11_web-scraping/01_web-scraping.html#5), [working with APIs](../materials-2023/11_web-scraping/03_api.html), [code from class](https://stat585-at-isu.github.io/materials-2023/code/code-2023-04-04.R) |
12        | Event driven programming                                     | **Apr 6** Hands-on session: Project check-in. Make sure to prep some questions!  
&nbsp;    | &nbsp;                                                       | **Apr 11** [Intro to shiny apps](../materials-2023/10_interactive/01_shiny.html), [zipped folder of example apps](../materials-2023/10_interactive/shiny.zip), [Dashboards](../materials-2023/10_interactive/02_shiny.html) 
&nbsp;    | &nbsp;                                                       | **Apr 13** Lab 4: [a shiny app](labs/04-lab-slides.qmd)
13        | Parsing data, profiling code                                 | **Apr 18** More data-scraping: [working with APIs](../materials-2023/11_web-scraping/03_api.html), [regular expressions](../materials-2023/07_regular-expressions/01_regular-expressions.html)
&nbsp;    | &nbsp;                                                       | **Apr 20**
14        | Databases                                                    | **Apr 25** 
&nbsp;    | &nbsp;                                                       | **Apr 27**
15, Finals | Project Presentations                                       | **May 2**
&nbsp;    | &nbsp;                                                       | **May 4**
&nbsp;    | &nbsp;                                                       | **May 11, 12-2pm**