---
layout: blog
topic: "02"
short-topic: Happy git and GitHub
due-date: 2023-02-02
root: ../../
---

## Prompt:

git and Github are tools for helping with versioning of files in collaborative efforts as well as archiving entries for your future self. 
Unfortunately working with git isn't always completely straightforward. 
Jenny Bryan's book "Happy git and github with R" helps with that. The book is available from [http://happygitwithr.com/](http://happygitwithr.com/). Have a look over the index and pick one of the chapters for a more in-depth read.

Write a blog post answering the following questions: 

1. **Write a short (100-150 words) summary of the chapter you read in-depth.**

I finished reading Happy Git and GitHub for the use R, chapter 4. Creating a GitHub account is covered in the fourth chapter. I already had a little basic knowledge of Git and GitHub, but I'm always looking to learn more.
Everyone can register at GitHub for free from [here](https://github.com/).
I discovered that a GitHub username should:

 - Include real name and be original, brief, and simple to read.
 - not be tied to time, the school's name, etc.
 - not include uppercase and lowercase letters, use hyphens to separate words.
 - be a good username while you can modify your username anytime later.
 
GitHub provides unlimited free private repositories with a maximum of three external collaborators. If you are an academic member, educational/research staff member, or student, you can also take advantage of [GitHub Education](https://education.github.com/).
formally recognized charities and nonprofits can benefit from [GitHub for Good](https://github.com/nonprofit).
You must purchase plans with a number of [advanced features](https://help.github.com/articles/github-s-products/#github-pro) if you require private repositories with more than three external collaborators.Current plans and pricing information is available [here](https://github.com/pricing).

2. **Looking back at all of the team projects you have been involved in, describe the biggest mishap you had. Could that have been avoided using git? How?**. 

Most of the time, in our team projects, we face challenges that can be avoided by using GitHub. For example, in a team project I am currently working on, we upload our updated presentations in a shared Box folder. We created different sub folders for different collaborators, and each member should upload her/ his files in a specific folder mentioning its date and time. Now all of these files can be uploaded to a private repository, and everyone in the team can see changes with their related date and time and the member who made those changes. In this way, every document can be accessible easier for all the team members, and later, the team can make this repository public if possible, and others can also use the information you found and not reinvent the wheel.

3. **Give an example of one new git feature that you learned about from Jenny Bryan's book.**.

I could not read all the chapters from the book, but it is very interesting that I found that GitHub can be connected with Rstudio. We can easily use these two for our projects. Regarding chapter 15 in the book, it seems that we can make changes in R studio and then commit the changes to the local repository, and then we can push our local changes to GitHub.

