---
author: Sabrena Rutledge
date: 2023-01-26
category: "Asking Good Questions"
title: Asking Good Questions
---

## Prompt:

Asking good questions is a valuable skill to have - asking questions in an online setting is both easier and harder than asking questions in person: we can prepare to ask a question but we are also expected to prepare.
The links posted here give some advice on how to ask good questions:

- stackoverflow's [Asking a good question](http://stackoverflow.com/help/how-to-ask)

- R's [Posting guidelines](https://www.r-project.org/posting-guide.html)

- [minimal complete verifiable example](https://stackoverflow.com/help/mcve), [minimal reproducible example](https://www.tidyverse.org/help/)

Follow these links and read through the advice given, then

1. **Pick at least one question from stackoverflow or the R help and answer it.**

Write a blog post answering the following questions: 

2. **Document which question you answered (link to your answer).**
I answered the question linked below:
(https://stackoverflow.com/questions/75248261/cant-install-packages-in-r)
https://stackoverflow.com/questions/75248261/cant-install-packages-in-r/75251062#75251062

3. **Relate your experience of answering the question to your reading. **
 
I chose an installation issue question, where the person asking was having issues installing a specific package. Answering the question I chose was rather straight-forward, since the answer to their question was hidden in the midst of their error message. 
According to stackoverflow's Asking a good question page, authors should "explain how [they] encountered the problem [they are] trying to solve, and any difficulties that have prevented [them] from solving it [themselves]." Yet, the author of this particular question appears to only have attemptted installing twice before giving up. They go on to say "Any package I try to install raises the same issue," which cannot be true since the error message is specific to the package and its dependencies. 
As such, I'm not sure if their question was helpful to resolving their issue, since there seemed to issues with not having admin rights that was complicating the installation process. In conclusion, I don't think this question should have been posted on StackOverflow and should have been directed to the author's IT department.



<!--Go to [https://github.com/Stat585-at-ISU/blog](https://github.com/Stat585-at-ISU/blog) for instructions about how to prepare and submit your blog post.-->
Instructions to follow.
