---
author: Matt Kavanaugh
date: 2023-01-26
categories: "Asking Good Questions"
title: Asking Good Questions
---


## Prompt:

Asking good questions is a valuable skill to have - asking questions in an online setting is both easier and harder than asking questions in person: we can prepare to ask a question but we are also expected to prepare.
The links posted here give some advice on how to ask good questions:

- stackoverflow's [Asking a good question](http://stackoverflow.com/help/how-to-ask)

- R's [Posting guidelines](https://www.r-project.org/posting-guide.html)

- [minimal complete verifiable example](https://stackoverflow.com/help/mcve), [minimal reproducible example](https://www.tidyverse.org/help/)

Follow these links and read through the advice given, then

1. **Pick at least one question from stackoverflow or the R help and answer it.**

Write a blog post answering the following questions: 

2. **Document which question you answered (link to your answer).**

I answered the following question on StackOverflow: https://stackoverflow.com/questions/75239069/error-matrix-must-have-equal-dimensions-despite-seemingly-equal-dimensions/75239932#75239932

3. **Relate your experience of answering the question to your reading. **

When answering this question, I took advantage of what the asker did provide in terms of a of a minimal, reproducible example. The asker provided a sufficient amount of code that was necessary to answer the question. This code was also very well organized and grouped into small chunks. The included code was also relevant to the issue at hand, and extraneous details were omitted. As a result, I was able to test out similar code myself with a sample program to determine whether my solution was plausible. Additionally, I was able to compare my solution with related questions and answers presented by other StackOverflow users.
  However, the asker did not provide the specific R package they used to fit their model. Hence, I was unable to know for sure whether the issue was related to the data in their test matrix or if it was instead an issue with the way they were using a certain package. The question only included small amounts of code and a brief description of the issue. Additionally, no comments were included for the code that was included, which made it difficult to understand all lines of code with this package that I was seemingly unfamiliar with. 
  Fortunately, the problem appeared to be quite self-explanatory and required few additional details. When answering the question, I asked for additional clarification on the R package that they used so that myself or another user can provide a more detailed solution (if my solution does not solve their issue). The problem should then be easily solved by another user who has a greater degree of familiarity with the associated package.

<!--Go to [https://github.com/Stat585-at-ISU/blog](https://github.com/Stat585-at-ISU/blog) for instructions about how to prepare and submit your blog post.-->
Instructions to follow.
