---
author: "AA"
date: 2023-02-09
categories: "Building a Book"
title: "Building a Book"
---

## Prompt:


The goal of this  week's blog is to document what you are doing when things do not go according to plan. 

Similar to previous exercises, we have a specific use case in mind: we want to build a book from a github repository. 

What happens in practice usually, is that we run into some problems. 
So your real task turns into that of a bug-hunter and fixer. Luckily, you have a community (the class discussion board) who might be able to help you. 



### What we want: build a book

Build the html version of the 2nd edition for Hadley Wickham's book `Advanced R Programming` from a github repository.

Steps:

1. Clone the repository `https://github.com/hadley/adv-r`.
2. Open the R project in the repository in RStudio.
3. Activate the `Build` tab (by default in the top right panel). Click on the `Build Book` button.
4. The book will be available in html format as index.html

**Deliverable (1):** what is the last word in chapter 15? - You don't have to answer this question, if things don't work. 

"15.6.3 Exercises
What would a full setOldClass() definition look like for an ordered factor (i.e. add slots and prototype the definition above)?

Define a length method for the Person class." ... The last word in chapter 15 is 'class'.

### What to do when things don't work?

Errors happen, they are frustrating, but if we learn something from them, we can turn them into valuable experiences.

- check the Questions and Answers forum in Canvas whether there is a solution available for your problem. 

- if the above document does (not yet) include your question, document the error you encounter (be as concise and specific as you can at the same time)

- if the Question and Answers forum does (not yet) include a solution, describe one approach on how you tried to solve the problem (and how this did not work).

- submit the description of your problem in Canvas at Discussions > Questions and Answers.  Write the paragraph in the mindset that you want to get help from somebody, and you try to describe the problem you are encountering. 

- Extra points (1 pt for the first suggested working solution): post a solution to one of the problems in the Questions and Answers forum (your own does not count!). 


**Deliverable (2):** Write a paragraph on the biggest problem you encountered when you were building the book, (and how you managed to solve it.)

Of the problems that I encountered when building the book, the biggest problem I had may likely have been one of the smallest... not having required packages downloaded. I encountered similar errors to others from the class through the building process but was able to trace them back and fix them quickly and without much issue. The error messages were helpful and made it easy for me to find where the issues were occurring in the various markdown files. What I found the most challenging for myself was feeling like everything was working and I had fixed everything just for the process to fail again due to not having a package that was being pulled from the library. This was of course easily fixed through downloading the package it was looking for, but it was more of an annoyance than anything else. Following through this blog and being able to successfully build the book myself was encouraging though and I now feel that I am more knowledgeable for when errors may appear in my own projects in the future. I have more experience now using search engines and asking proper questions to my peers if issues present themselves in the future. 

Submit to your repo and you are done!

