---
author: Motahareh Kashanian
date: 2023-01-26
categories: "Asking Good Questions"
title: Asking Good Questions
---

## Prompt:

Asking good questions is a valuable skill to have - asking questions in an online setting is both easier and harder than asking questions in person: we can prepare to ask a question but we are also expected to prepare.
The links posted here give some advice on how to ask good questions:

- stackoverflow's [Asking a good question](http://stackoverflow.com/help/how-to-ask)

- R's [Posting guidelines](https://www.r-project.org/posting-guide.html)

- [minimal complete verifiable example](https://stackoverflow.com/help/mcve), [minimal reproducible example](https://www.tidyverse.org/help/)

Follow these links and read through the advice given, then

1. **Pick at least one question from stackoverflow or the R help and answer it.**

Write a blog post answering the following questions: 

2. **Document which question you answered (link to your answer).**

Below is the link to one of the questions I answered on StackOverflow
(https://stackoverflow.com/questions/74797820/find-value-in-matrix-starting-from-two-columns-value/75253008#75253008)

3. **Relate your experience of answering the question to your reading. **
 
 My attempt was to answer a question to which I knew the answer. To be honest, finding a question that I can answer has been challenging! It took me most of my time to find a question :)

In answering the question, I tried to be clear, concise, and complete. According to StackOverflow's structure, I provided reproducible code and a formatted answer.


<!--Go to [https://github.com/Stat585-at-ISU/blog](https://github.com/Stat585-at-ISU/blog) for instructions about how to prepare and submit your blog post.-->
Instructions to follow.
