---
author: Anisi Atefeh
date: 2023-01-26
categories: "Asking Good Questions"
title: Asking Good Questions
---

## Prompt:

Asking good questions is a valuable skill to have - asking questions in an online setting is both easier and harder than asking questions in person: we can prepare to ask a question but we are also expected to prepare.
The links posted here give some advice on how to ask good questions:

- stackoverflow's [Asking a good question](http://stackoverflow.com/help/how-to-ask)

- R's [Posting guidelines](https://www.r-project.org/posting-guide.html)

- [minimal complete verifiable example](https://stackoverflow.com/help/mcve), [minimal reproducible example](https://www.tidyverse.org/help/)

Follow these links and read through the advice given, then

1. **Pick at least one question from stackoverflow or the R help and answer it.**

Write a blog post answering the following questions: 

2. **Document which question you answered (link to your answer).**

I answered one question in StackOverflow, here is the [link](https://stackoverflow.com/questions/46681813/for-loop-with-if-statements-both-iterates-over-a-list-gave-warnings-in-r/75240425#75240425) to the question. 

My StackOverflow profile is Atefeha1995.

3. **Relate your experience of answering the question to your reading. **
 
This is the first time I am working on the StackOverflow website. Based on my reading, the questions and answers on this website need to follow special instructions. I tried to answer a question that I know the answer to while making sure that:

- My answer is short, complete, and clear.

- I followed the StackOverflow structure for writing.

- My answer and code are reproducible.

- I included the code sample regarding the required code formatting, etc.


<!--Go to [https://github.com/Stat585-at-ISU/blog](https://github.com/Stat585-at-ISU/blog) for instructions about how to prepare and submit your blog post.-->
Instructions to follow.