---
author: Charlie Bonk
date: 2023-01-26
category: "Asking Good Questions"
title: Asking Good Questions
---

## Prompt:

Asking good questions is a valuable skill to have - asking questions in an online setting is both easier and harder than asking questions in person: we can prepare to ask a question but we are also expected to prepare.
The links posted here give some advice on how to ask good questions:

- stackoverflow's [Asking a good question](http://stackoverflow.com/help/how-to-ask)

- R's [Posting guidelines](https://www.r-project.org/posting-guide.html)

- [minimal complete verifiable example](https://stackoverflow.com/help/mcve), [minimal reproducible example](https://www.tidyverse.org/help/)

Follow these links and read through the advice given, then

1. **Pick at least one question from stackoverflow or the R help and answer it.**
  - Okay, so I looked at all of the R questions and even with my relatively decent knowledge of R, I have no idea the back end of things and I thought I could maybe answer a question on R on MacOS since I have dealed with a lot of issues, but I got super anxious and scared about answering any of the questions, so I just went to a LaTeX question (which is still kind of R adjacent becuase maybe they are working in a .qmd file?) and answered it.


Write a blog post answering the following questions: 

2. **Document which question you answered (link to your answer).**
  - [Link to my answer](https://stackoverflow.com/questions/75177244/how-do-i-remove-a-number-before-a-section-in-latex/75253440#75253440)

3. **Relate your experience of answering the question to your reading. **
  - One thing about the question that I answered is that the answer to it is really easy to find online. Like, I'm not sure if the user looked elsewhere before asking on StackOverflow. Simply Googling "How to remove the numbering before a section in LaTeX" pulls up an Overleaf site with the answer. So if I were that person, I would have first looked elsewhere. 
  - The question asker also could have done a little better with include all relevant code in order to answer their solution. They included just the part that was giving them trouble, when a document class and some of the packages being used would have been helpful. I assumed they were working on an article as it is the most common, but the answer should apply across all classes.
  - If I could talk to them face-to-face, I would have pointed them to other sources (i.e. Overleaf) for most of their questions, since their documentation is really good for quick-access LaTeX questions. If they were also working in somehting like R with a Quarto document, I know Quarto's website also has a plethora of knowledge.
  - One thing the readings did not tell you is that answering on StackOverflow is **SO SCARY** like I haven't been as stressed out about anything before. Like, what is too little to add? Is saying that ```{python}`` ` (without the space) is another way to quickly access Python in a .Rmd document, when someone already spoke about the code you can run in a R session with the 'reticulate' package? Also I was and still am afraid that I made a mistake with my answer and it is wrong or not what they needed and then my answer will get down-voted to the deepest depths.
  - I'm just too timid to ask questions on StackOverflow, but also too timid to answer them.
 

<!--Go to [https://github.com/Stat585-at-ISU/blog](https://github.com/Stat585-at-ISU/blog) for instructions about how to prepare and submit your blog post.-->
Instructions to follow.
