---
author: "Ian Parzyszek"
title: "Web scraping etiquette ..."
categories: "Web scraping etiquette ..."
date: "2023-04-06"
output: github_document
---
 
## Prompt:

With great power comes great responsibility - a large part of the web is based on data and services that scrape those data. 
Now that we start to apply scraping mechanisms, we need to think about how to apply those skills without becoming a burden to the internet society.

Find sources on ethical web scraping - some readings that might help you get started with that are: 

  - [James Densmore](https://towardsdatascience.com/ethics-in-web-scraping-b96b18136f01)

  - R package [polite](https://github.com/dmi3kno/polite)

  - [JAMI @ EMPIRICAL](https://www.empiricaldata.org/dataladyblog/a-guide-to-ethical-web-scraping)


After reading through some of the ethics essays
write a blog post addressing the following questions: 

1. **What are your main three takeaways for ethical web scraping? - Give examples, or cite your sources.**

One of the first things I was unaware of was that webscraping can be a burden on the server. I did not think it was anymore cumbersome for the server than just visiting the website, but because this is not the case good practice is to conduct scraping during non-busy times.

Another good practice is to identify yourself. The websites owner may see some unusual activity, so it can be a good idea to give a string in your code to identify yourself, and maybe also let them know your intentions.

Lastly, you should give back to the website owner and give them credit. If you are using their data, cite their website/article. This will help give their website some more traffic.

I got these takeaways from :[JAMI @ EMPIRICAL](https://www.empiricaldata.org/dataladyblog/a-guide-to-ethical-web-scraping)


2. **What is a ROBOTS.TXT file? Identify one instance and explain what it allows/prevents.**

A ROBOTS.TXT files is put in place to put limitations on what crawlers can access on their website. An example would be including a ROBOTS.TXT file to limit the amount of information a search engine can search on your website and include in their results. Sometimes you may want GOOGLE to avoid including PDFs or pictures, so you could include a ROBOTS.TXT file to prevent this.

3. **Identify a website that you would like to scrape (or one an example from class) and implement a scrape using the `polite` package.**

Instructions:

Submit to your repo. Make sure that all of the github actions pass (check menu item Actions - all of the actions should have green checks)

```{r}
library(polite)
library(rvest)
session <-  bow("https://www.avca.org/polls/diii-men/2023/03-28-23.html")
scrape(session) %>%
  html_table()
  
#Here is the Division 3 Men's Volleyball National Rankings...Messiah University is ranked 5! Go Falcons!!!!!

```

