---
author: Celik Harun
date: 2023-01-26
category: "Asking Good Questions"
title: Asking Good Questions
---

## Prompt:

Asking good questions is a valuable skill to have - asking questions in an online setting is both easier and harder than asking questions in person: we can prepare to ask a question but we are also expected to prepare.
The links posted here give some advice on how to ask good questions:

- stackoverflow's [Asking a good question](http://stackoverflow.com/help/how-to-ask)

- R's [Posting guidelines](https://www.r-project.org/posting-guide.html)

- [minimal complete verifiable example](https://stackoverflow.com/help/mcve), [minimal reproducible example](https://www.tidyverse.org/help/)

Follow these links and read through the advice given, then

1. **Pick at least one question from stackoverflow or the R help and answer it.**

Write a blog post answering the following questions: 

2. **Document which question you answered (link to your answer).**

3. **Relate your experience of answering the question to your reading. **
 

<!--Go to [https://github.com/Stat585-at-ISU/blog](https://github.com/Stat585-at-ISU/blog) for instructions about how to prepare and submit your blog post.-->
Instructions to follow.

Harun's Blog

I chose to answer a question from StackOverflow because I have used the forum as a resource plenty of times in the past but never contributed. The question I answered was [this one](https://stackoverflow.com/questions/75240637/using-a-list-of-variables-in-a-loop/75241256#75241256) about using a list of variables in a loop in R. My username is HarunCelikOtto and is chronologically the second answer to the question. 

I think that after reading the advice by Stack Overflow's "How do I ask a good question?" I came to better understand why I had trouble understanding the question that the user posted on the forum. While the inquirer added some example code about what data they were working with, they didn't elaborate on the outcome that was expected of the corrected code. For this reason, another user and myself had to assume what the intended output had to be. While the user may find my answer helpful, maybe it isn't exactly the result that they want because the objective was unclear. Looking through questions, I've come to the realization after this activity that only a good question can elicit a good response.
