---
author: Alexadra Arabio
date: 2023-02-02
categories: "Happy Git with R"
title: Happy Git with R
---

## Prompt:

git and Github are tools for helping with versioning of files in collaborative efforts as well as archiving entries for your future self. 
Unfortunately working with git isn't always completely straightforward. 
Jenny Bryan's book "Happy git and github with R" helps with that. The book is available from [http://happygitwithr.com/](http://happygitwithr.com/). Have a look over the index and pick one of the chapters for a more in-depth read.

Write a blog post answering the following questions: 

1. **Write a short (100-150 words) summary of the chapter you read in-depth.**

Chapter 22: Branches
The concept of branching allows an individual to 'branch out' from the main project to explore their own idea without anything happening to the original or main working code. Git works with this concept seamlessly allowing for branches to open and merge back quickly. One can create their own branch, switch between branches, and merge a branch with only a line of code. This chapter also explains how to deal with possible issue that may occur and recognizes that a conflict does not mean a disaster (this is often why we use branches... to avoid disaster). One of the main reasons for branching is to allow for brainstorming, consideration, and implementing new ideas... this is how progress is made.

2. **Looking back at all of the team projects you have been involved in, describe the biggest mishap you had. Could that have been avoided using git? How?**. 

Through majority of the team projects that I have been involved in, the largest mishap occurs from 'stepping on each others toes'... When working in a group where everyone wants to be able to get something accomplished to achieve the best possible outcome, it can be subjective to each individual. When working on PowerPoint slides or writing a report; people tend to have differences in opinions on what the best layout is or the best wording for certain sentences. This is where I have found the greatest conflict because it becomes difficult if we are all working on the same document to change things without the work of others getting loss in the process and work may get lost. This problem could possibly be able to be avoided using git as it has its own system for backing up previous work, seeing who made changes, and when they were made. 

3. **Give an example of one new git feature that you learned about from Jenny Bryan's book.**.

I have not read Jenny Bryan's book previously and found it to be a great resource. Though I knew the general basics of git, I appreciated that the book walked through the processes of learning git and showed it truly as a processes and that confusion is okay and expected. Because of this I learned more about possible errors that could occur throughout the merging process and how to tackle them if they present themselves as issues. I also learned through this book that it is better to start a new project on GitHub first prior to working in a new project in R. 
