---
author: "Kundan Kumar"
date: 2023-01-26
categories: "Asking Good Questions"
title: Asking Good Questions
---

## Prompt:


1. **Pick at least one question from stackoverflow or the R help and answer it.**

Write a blog post answering the following questions: 

I have asked a question about how to detect objects in a video using python. Please find the [Link](https://stackoverflow.com/questions/75253102/detect-objects-in-a-video) 

Moreover, I have answered on question in R, in which i plotted a pie chart.Please find the  [Link](https://stackoverflow.com/questions/75178249/pie-chart-legend-with-multiple-lines-of-text-in-r/75178711#75178711)


2. **Document which question you answered (link to your answer).**

I have answered a question how to create Pie chart legend with multiple lines of text in R. User is facing an issue that multiple lines of text will out of legend. Please find the [Link](https://stackoverflow.com/questions/75178249/pie-chart-legend-with-multiple-lines-of-text-in-r/75178711#75178711)

I have explored the the package 'ggplot2' and 'ggrepel' and finally plotted the pie chart in which multiple lines of text are within the legend.


3. **Relate your experience of answering the question to your reading. **
 
As the start, i was just plotting it seems fine to me, but seems i didn't understand the problem well.
I was only using the basic R functionality for plotting the pie chart and i literally struggle alot.
 
After understanding the problem well, i explored the R packages and implemented the code successfully and plotted the pie chart along the legend precisely. It is a great learning curve for me and hopefully enhanced my skill a bit.
 
 

