---
author: Anyesha Ray
date: 2023-01-26
category: "Asking Good Questions"
title: Asking Good Questions
---

## Prompt:

Asking good questions is a valuable skill to have - asking questions in an online setting is both easier and harder than asking questions in person: we can prepare to ask a question but we are also expected to prepare.
The links posted here give some advice on how to ask good questions:

- stackoverflow's [Asking a good question](http://stackoverflow.com/help/how-to-ask)

- R's [Posting guidelines](https://www.r-project.org/posting-guide.html)

- [minimal complete verifiable example](https://stackoverflow.com/help/mcve), [minimal reproducible example](https://www.tidyverse.org/help/)

Follow these links and read through the advice given, then

1. **Pick at least one question from stackoverflow or the R help and answer it.**

Write a blog post answering the following questions: 

2. **Document which question you answered (link to your answer).**
https://stackoverflow.com/questions/75204993/merge-two-csv-files-based-on-row-information/75205639#75205639
3. **Relate your experience of answering the question to your reading. **
 
 Based on my reading there are a couple things that we should do when asking a question:
- Make sure your question is on-topic and suitable for this site
- Search, and research
- Write a title that summarizes the specific problem
- Introduce the problem before you post any code
- Help others reproduce the problem
- Include all relevant tags
- Proofread before posting
- Respond to feedback after posting
-(From https://stackoverflow.com/help/how-to-ask)

The question I answered would not be considered a good  question. While the question was on topic and had an appropriate title, it was not researched and not reproducible. The question was about merging two csv files, and I am sure that question has already been asked before. Also, they gave a description of the data, but it was not very detailed. I answered the question based on what I assumed the data looked like, but the question could have been more descriptive. From looking around on Stack Exchange, it is more difficult than you think to ask a good question. 




<!--Go to [https://github.com/Stat585-at-ISU/blog](https://github.com/Stat585-at-ISU/blog) for instructions about how to prepare and submit your blog post.-->
Instructions to follow.
