---
title: "Website Blog"
author:  "AR"
date: "2023-03-23"
categories: "My professional self"
output: github_document
---

## Prompt:

GitHub is an incredibly useful tool for project management and collaboration. It also has several useful features for professional promotion: you can host your own site on github using [GitHub pages](https://pages.github.com/), describe yourself using a GitHub developer profile, and even use [resume.github.io](http://resume.github.io/) to generate a resume summary of your activity on GitHub (you must opt-in by [starring the project page](https://github.com/resume/resume.github.com)). 

posit and the associated package infrastructure provide multiple ways to generate websites using Quarto (or Rmarkdown). You can complete this assignment using one of the two options detailed in [Prompt 8](https://stat585-at-isu.github.io/blog-2023/Prompts/Blog-8/Prompt.html)

Describe your experience creating your website below. Don't forget to link to your website! Push this blog post to your blog-8 repo. Make sure that all of the checks are passing.

**How did building your own website go?**

It went okay. The actual building of the websit was fine, however it was  very difficult to push the changes. The sites_libs folder did not want to push.  I finally was able to through the terminal. Also, I was confused as to how we get to the website.  
