---
author: Bhagat Sudesh
date: 2023-01-26
categories: "Asking Good Questions"
title: Asking Good Questions
---

## Prompt:

Asking good questions is a valuable skill to have - asking questions in an online setting is both easier and harder than asking questions in person: we can prepare to ask a question but we are also expected to prepare.
The links posted here give some advice on how to ask good questions:

- stackoverflow's [Asking a good question](http://stackoverflow.com/help/how-to-ask)

- R's [Posting guidelines](https://www.r-project.org/posting-guide.html)

- [minimal complete verifiable example](https://stackoverflow.com/help/mcve), [minimal reproducible example](https://www.tidyverse.org/help/)

Follow these links and read through the advice given, then

1. **Pick at least one question from stackoverflow or the R help and answer it.**
After reading the content on both the links, the question I chose to answer was from Stackoverflow(https://stackoverflow.com/questions/61086231/writing-a-for-loop-in-r-for-knn-method-with-cross-validation?noredirect=1#comment108075908_61086231) and R help(https://community.rstudio.com/t/converting-factor-variable-into-numeric/158479). 

Write a blog post answering the following questions: 

2. **Document which question you answered (link to your answer).**
After reading the content on both the links, the question I chose to answer was from Stackoverflow(https://stackoverflow.com/questions/61086231/writing-a-for-loop-in-r-for-knn-method-with-cross-validation?noredirect=1#comment108075908_61086231) and R help(https://community.rstudio.com/t/converting-factor-variable-into-numeric/158479). 
The link to my answer to the questions I answered is already provided in the first part as well as here and here. My ID for the question and answer on Stackoverflow(https://stackoverflow.com/questions/61086231/writing-a-for-loop-in-r-for-knn-method-with-cross-validation?noredirect=1#comment108075908_61086231) is user13073332 whereas on R help is Sudi. I had asked this question on Stackoverflow and I landed up answering it, following a discussion about it on Stackoverflow. As a result, my answer is also provided under the question

3. **Relate your experience of answering the question to your reading. **

 My experience of answering the question based on the reading. When I had answered this question, I was not aware of the correct way to ask questions. Based on the readings, the question asked meets the first criterion for a good question, which is that the question should be on topic and suitable to the Stackoverflow website.The portal Stackoverflow invites questions about programming and the question asked met this requirement. 
 The second requirement is to research and search the existing set of questions to ensure that the question you intend to ask is not duplicated. Although the questioner (which, in this case, was me) had researched and searched the existing set of questions to look for a suitable answer, there is no proof provided to indicate that the question was not repeated/duplicated. The questioner had not linked any seemingly similar questions on this topic existing on the portal. It could also be that there were no such questions. 
 Thereafter, another requirement is that the title of the question summarizes the specific problem faced by the researcher. This condition is not met by the questioner as the title could appear a vague and ambiguous to those attempting to answer the question, although the question itself carries some details, if not all. 
This is why the person attempting to answer this question asked counterquestions for further clarification. While offering clarification to the question, I stumbled upon the answer myself and answered it on the portal as user13073332. With this experience of asking and answering questions, I learned the importance of providing all possible details required to answer the questions satisfactorily. A question that is clear begets answers whereas one that is unclear only invites further questions.
I would also like to link another question I had answered on R help. In this case, the questioner was not me but I had provided the answer under the name “Sudi”.  
The title of the question is not clear to the extent that there is no indication that it may be a question related to R as required by the guidelines of the portal. However, the person asking the question provides all the required information as part of the question, albeit leaving room for grammatical correction. No vignettes or code demonstrations were provided. 
The questioner did not allude to other similar questions on the portal or their search about such questions. As I was the second person answering this question, I had help in the form of the answer from the person who had attempted the question before me. Their answer had code information, which was useful while providing an answer.

<!--Go to [https://github.com/Stat585-at-ISU/blog](https://github.com/Stat585-at-ISU/blog) for instructions about how to prepare and submit your blog post.-->
Instructions to follow.
