---
author: Gino Beltran
date: 2023-02-02
categories: "Happy Git with R"
title: Happy Git with R
due-date: 2023-02-02
root: ../../
---

**Summary of Chapter 6.  Install Git.

This chapter includes instructions on how to install Git Bash.  Given that I am new to Github and Git, I found it somewhat confusing at first.  I had watched YouTube videos to familiarize myself with github and run into several videos about Git Bash, but did not know what it was, so after I completed the instructions in the book and installed Git in my PC, I then realized they were the same. After reading this chapter in more detail, I learned that Git has multiple names. 

Summary.

1.	Verify if you already have Git and consider updating if you have an older version.

git --version
## git version 2.39.1

2. Install Git for Windows.

Option 1 (highly recommended) from the link below (I used this option):
https://gitforwindows.org/
Option 2 (recommended): Install Git for Windows via the Chocolatey package manager. I personally did not use this option.
choco install git.install

3.	Updating Git for Windows if you have an old version.
git update-git-for-windows

The rest of the chapter if for Mac and Linux users, which I didn’t use.

**Biggest Mishap Experience.

I have worked on a number of projects, big and small, but I have no experience working on coding or software development projects.  It seems to me, git and github apply the concepts of “document control” and “versioning” to coding, which allows the user to have one source of truth while cooperate with others.  I have used other tools such as MS Project, SharePoint, SAP/R3, and more recently MS OneDrive for the same purpose of document control and cooperation.  I have had no big mishap so far.  However, I can mention that when not using these tools, authoring with others, a new document for instance, can be significantly more troublesome and painful.  Just having the ability to go back to a previous version can be a life saver. 

**Git Example of One New Feature.

Everything from Git and the book was new to me, but I can highlight I didn’t know about the capability of R to be connected with github to work in a team environment. 


## Prompt:

git and Github are tools for helping with versioning of files in collaborative efforts as well as archiving entries for your future self. 
Unfortunately working with git isn't always completely straightforward. 
Jenny Bryan's book "Happy git and github with R" helps with that. The book is available from [http://happygitwithr.com/](http://happygitwithr.com/). Have a look over the index and pick one of the chapters for a more in-depth read.


Write a blog post answering the following questions: 

1. **Write a short (100-150 words) summary of the chapter you read in-depth.**
2. **Looking back at all of the team projects you have been involved in, describe the biggest mishap you had. Could that have been avoided using git? How?**. 
3. **Give an example of one new git feature that you learned about from Jenny Bryan's book.**.
