---
author: Valerie Han
date: 2023-01-26
categories: "Asking Good Questions"
title: Asking Good Questions
---

## Prompt:

Asking good questions is a valuable skill to have - asking questions in an online setting is both easier and harder than asking questions in person: we can prepare to ask a question but we are also expected to prepare.
The links posted here give some advice on how to ask good questions:

- stackoverflow's [Asking a good question](http://stackoverflow.com/help/how-to-ask)

- R's [Posting guidelines](https://www.r-project.org/posting-guide.html)

- [minimal complete verifiable example](https://stackoverflow.com/help/mcve), [minimal reproducible example](https://www.tidyverse.org/help/)

Follow these links and read through the advice given, then

1. **Pick at least one question from stackoverflow or the R help and answer it.**

Write a blog post answering the following questions: 

2. **Document which question you answered (link to your answer).**

https://stackoverflow.com/questions/75241167/looping-through-r-dataframe-columns/75241265#75241265

3. **Relate your experience of answering the question to your reading. **
 
Choosing a question to answer and actually trying to answer it helped me understand how important a minimal reproducible example is. I also appreciated the informative titles of questions. Both helped me quickly assess if a question was something I could solve using my own experience and made me want to answer their questions more, making clear to me why the readings have such guidelines for posting questions.

The question I chose to answer was relatively simple with only 6 lines of code.  However, when trying to answer their question, I realized that their example was not reproducible for others because they didn't include a dataset that corresponded to their variable in the code. I ended up creating my own little example to try to understand what their issue was. In doing so, I also realized that, as the readings said, making a minimal reproducible example isn't always that hard and that trying to make one can help you think through your bug as well.



<!--Go to [https://github.com/Stat585-at-ISU/blog](https://github.com/Stat585-at-ISU/blog) for instructions about how to prepare and submit your blog post.-->
Instructions to follow.
