---
author: Logan Johnson
date: 2023-01-26
category: "Asking Good Questions"
title: Asking Good Questions
---

## Prompt:

Asking good questions is a valuable skill to have - asking questions in an online setting is both easier and harder than asking questions in person: we can prepare to ask a question but we are also expected to prepare.
The links posted here give some advice on how to ask good questions:

- stackoverflow's [Asking a good question](http://stackoverflow.com/help/how-to-ask)

- R's [Posting guidelines](https://www.r-project.org/posting-guide.html)

- [minimal complete verifiable example](https://stackoverflow.com/help/mcve), [minimal reproducible example](https://www.tidyverse.org/help/)

Follow these links and read through the advice given, then

1. **Pick at least one question from stackoverflow or the R help and answer it.**

Write a blog post answering the following questions: 

2. **Document which question you answered (link to your answer).**

The question that I chose was related to graphing data and the ability to use ggplot2 to visualize this data. The link to the post is included [here](https://stackoverflow.com/questions/75253491/how-do-i-plot-a-scatterplot-graph-with-a-repeated-measures-variable-and-a-contin/75254525#75254525). The question did not provide an example of their data or any code they had been working with. 

3. **Relate your experience of answering the question to your reading. **

In reading the examples of asking a good question on stackoverflow and the other links provided, it is clear that you must include a sufficient amount of background on the question you are asking. This can be an overview of the question you have, some example of the data, and some of the code that you have been using. In the example that I had, there was none of this. The person had 3 sentences and vagely described their problem. I did my best to answer their question, provide a link to ggplot2 cheat sheets, and provide some potential examples. 
 

<!--Go to [https://github.com/Stat585-at-ISU/blog](https://github.com/Stat585-at-ISU/blog) for instructions about how to prepare and submit your blog post.-->
Instructions to follow.