---
layout: blog
topic: "02"
short-topic: Happy git and GitHub
due-date: 2023-02-02
root: ../../
---

## Prompt:

git and Github are tools for helping with versioning of files in collaborative efforts as well as archiving entries for your future self. 
Unfortunately working with git isn't always completely straightforward. 
Jenny Bryan's book "Happy git and github with R" helps with that. The book is available from [http://happygitwithr.com/](http://happygitwithr.com/). Have a look over the index and pick one of the chapters for a more in-depth read.

Write a blog post answering the following questions: 

1. **Write a short (100-150 words) summary of the chapter you read in-depth.**

## Chapter 5: Install or upgrade R and RStudio

**Install R from here: https://cloud.r-project.org

**Install RStudio from here: https://www.rstudio.com/products/rstudio/download/preview/

**Update your R packages: update.packages(ask = FALSE, checkBuilt = TRUE)

Using old versions of software can be a hassle. For the best experience, it's recommended to be on 4.something in R at this point. Keep at least one minor version up-to-date. Two minor versions behind will cause you problems as CRAN no longer supports pre-built binary add-on packages. Preview releases are similar to general releases, but they are used as release candidates in the build-up to new general releases. Preview version includes new features, but it is also very stable and highly usable. RStudio updates much more frequently than R itself. RStudio requires monthly updates, while R requires annual updates.

2. **Looking back at all of the team projects you have been involved in, describe the biggest mishap you had. Could that have been avoided using git? How?**. 
My last project was an interdisciplinary project in collaboration with chemical engineers, and we worked more often asynchronously than synchronously. When it comes to collaborating with distributed teams on projects, there are many challenges that must be overcome. The majority of the time I was unaware of their current changes in their experimental results, which had an effect on my results and added to my workload, as I had to go back and forth all the time to observe what they were doing. It is likely that GitHub could make this process much simpler in many ways, as it could track changes and go back to previous versions of a project, which would make the collaboration much easier.

3. **Give an example of one new git feature that you learned about from Jenny Bryan's book.**.
I Learn more about branches in this book. With Git, users have the option of working on a line that runs parallel to the main files of the project. Branch is the term used to describe these lines. As a feature of Git, branches provide a way for developers to modify the project without having to make any changes to the original version of the code. Whenever a version is being developed, a production quality branch of the code will always be present in the master branch. On the branches, you can test and work on any new features you will be launching and then you can merge them with the main branch as soon as they are ready. With the help of a few Git commands, branching and merging can be done very quickly and easily. There is a possibility that one version of a project may contain a number of different branches as per the requirements of the user.
